[package]
name = "vakantiehuis-dimitri"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = {version="0.5.1", features=["secrets", "json", "tls"]}
rocket_dyn_templates = {version="0.2.0", features=["handlebars"]}
surrealdb = "2.3.10"
